Banzzac-Developers/banzzac-server

- README.md
> feat : README.md

- src/main/java/banzzac/controll/DogController.java
- src/main/java/banzzac/controll/FriendController.java
- src/main/java/banzzac/controll/MemberController.java
- src/main/java/banzzac/dto/DogDTO.java
- src/main/java/banzzac/dto/FriendDTO.java
- src/main/java/banzzac/dto/MemberDTO.java
- src/main/java/banzzac/mapper/DogMapper.java
- src/main/java/banzzac/mapper/FriendMapper.java
- src/main/java/banzzac/mapper/MemberMapper.java
Controller , DTO, mapper 추가했습니다 .
> feat: Member,Dog,Friend 추가

- src/main/java/banzzac/controll/ChatController.java
- src/main/java/banzzac/dto/ChatDTO.java
- src/main/java/banzzac/dto/ChatroomDTO.java
- src/main/java/banzzac/mapper/ChatMapper.java
> feat: 채팅방 목록 및 채팅방 별 메세지 조회

- src/main/java/banzzac/dto/DogDTO.java
- src/main/java/banzzac/mapper/DogMapper.java
- src/main/java/banzzac/mapper/ProfileMapper.java
- src/main/java/banzzac/mapper/ReviewMapper.java
- src/main/java/banzzac/rest/ProfileController.java
- src/main/java/banzzac/rest/ReviewController.java
> feat : sql 작성중

- src/main/java/banzzac/dto/ChatDTO.java
- src/main/java/banzzac/dto/ChatroomDTO.java
- src/main/java/banzzac/mapper/ChatMapper.java
- src/main/java/banzzac/rest/ChatController.java
> feat: 채팅 내용 핑퐁핑퐁

- src/main/java/banzzac/dto/DogDTO.java
- src/main/java/banzzac/dto/PayApproveDTO.java
- src/main/java/banzzac/dto/PayInfoDTO.java
- src/main/java/banzzac/mapper/MemberMapper.java
- src/main/java/banzzac/mapper/ProfileMapper.java
- src/main/java/banzzac/mapper/ReviewMapper.java
- src/main/java/banzzac/rest/PaymentController.java
- src/main/resources/application.yml
> 결제API....ing

- src/main/java/banzzac/dto/DogDTO.java
- src/main/java/banzzac/dto/MatchingDTO.java
- src/main/java/banzzac/dto/MatchingSearchHistoryDTO.java
- src/main/java/banzzac/mapper/MatchingMapper.java
변경 예상 )
Matching DTO에 범위 설정용 Location DTO 추가.
Location 테이블과 Join.
후속 작업 )
Controller 작업 수행.
> feat/매칭 조건에 해당하는 멤버 정보 sql 작성 완료, Controller 작업 진행중

- src/main/java/banzzac/dto/DogDTO.java
- src/main/java/banzzac/dto/MemberDTO.java
- src/main/java/banzzac/mapper/FriendMapper.java
- src/main/java/banzzac/mapper/LoginMapper.java
- src/main/java/banzzac/mapper/MemberMapper.java
- src/main/java/banzzac/rest/FriendController.java
- src/main/java/banzzac/rest/LoginController.java
- src/main/java/banzzac/rest/MemberController.java
> feat: id,pw 찾기기능추가

- src/main/java/banzzac/config/WebSocketConfig.java
- src/main/java/banzzac/dto/ChatroomDTO.java
- src/main/java/banzzac/dto/DogDTO.java
- src/main/java/banzzac/mapper/ChatMapper.java
- src/main/java/banzzac/rest/ChatController.java
아이디가 참여중인 채팅방 목록 정보 프론트로 보내주기 완료
> 채팅방 목록 필요한 정보 뿌려주기 완료

- src/main/java/banzzac/dto/MemberDTO.java
- src/main/java/banzzac/mapper/FriendMapper.java
- src/main/java/banzzac/mapper/MemberMapper.java
- src/main/java/banzzac/rest/FriendController.java
- src/main/java/banzzac/rest/MemberController.java
> feat: pull을위한 푸쉬 별내용 없음

- src/main/java/banzzac/mapper/DogMapper.java
- src/main/java/banzzac/mapper/MemberMapper.java
- src/main/java/banzzac/rest/ProfileController.java
> feat : dogController reponseEntity 추가

- src/main/java/banzzac/dto/SessionDTO.java
- src/main/java/banzzac/mapper/DogMapper.java
- src/main/java/banzzac/mapper/LoginMapper.java
- src/main/java/banzzac/rest/LoginController.java
- src/main/java/banzzac/rest/MemberController.java
> feat:도그맵퍼,로그인컨트롤러수정

- src/main/java/banzzac/dto/RefundDTO.java
- src/main/java/banzzac/mapper/DogMapper.java
- src/main/java/banzzac/mapper/MemberMapper.java
- src/main/java/banzzac/mapper/PaymentMapper.java
- src/main/java/banzzac/rest/PayController.java
- src/main/java/banzzac/rest/ProfileController.java
> feat : refund sql 추가

- src/main/java/banzzac/controll/DashBoradController.java
- src/main/java/banzzac/dto/DashBoardDTO.java
- src/main/java/banzzac/mapper/AdminMapper.java
- src/main/resources/static/css/screen/dashboard.css
- src/main/resources/static/css/style.css
- src/main/webapp/views/dash/board.html
model 설정까지는 했다
이제 html에 뿌려주기만 하면 돼!
해내자!!!
> feat:dashboard 오늘의 신고 값 넣기만 하면 됌!

- src/main/java/banzzac/mapper/AdminMapper.java
- src/main/webapp/views/inc/aside.html
> feat/관리자 페이지 aside 링크 추가

- src/main/java/banzzac/mapper/FriendMapper.java
- src/main/java/banzzac/rest/KakaoController.java
- src/main/java/banzzac/rest/LoginController.java
> 수업종료전 풀을 위한 커밋

- src/main/java/banzzac/controll/MemberManagementController.java
- src/main/java/banzzac/dto/MemberDTO.java
- src/main/java/banzzac/dto/ReportDTO.java
- src/main/java/banzzac/mapper/AdminMapper.java
- src/main/java/banzzac/mapper/MemberMapper.java
- src/main/java/banzzac/rest/ChatController.java
채팅창에서  신고하기 추가 report 테이블 no 값들 id 로 변경
> feat/ 채팅창에서  신고하기 추가 report 테이블 no 값들 id 로 변경

- src/main/java/banzzac/config/WebSocketEventListener.java
- src/main/java/banzzac/mapper/ChatMapper.java
- src/main/java/banzzac/mapper/MemberMapper.java
- src/main/java/banzzac/rest/ChatController.java
- src/main/java/banzzac/utill/MessageType.java
> feat/chat controller 신고하기, 차단하기 추가

- src/main/java/banzzac/mapper/DogMapper.java
- src/main/java/banzzac/mapper/FriendMapper.java
- src/main/java/banzzac/rest/FriendController.java
- src/main/java/banzzac/rest/LoginController.java
> feat:회원가입수정

- src/main/java/banzzac/WebMvcConfig.java
- src/main/java/banzzac/mapper/FriendMapper.java
- src/main/java/banzzac/rest/FriendController.java
> feat:friend 컨트롤러세션적용

- src/main/java/banzzac/rest/FriendController.java
> feat:발표전 최종 커밋

- src/main/java/banzzac/mapper/AdminMapper.java
- src/main/java/banzzac/rest/ChatController.java
- src/main/java/banzzac/rest/LoginController.java
> feat/한거 없지만 일단 commit

- pom.xml
- src/main/java/banzzac/config/SecurityConfig.java
- src/main/java/banzzac/jwt/JwtAuthenticationFilter.java
- src/main/java/banzzac/jwt/JwtToken.java
- src/main/java/banzzac/jwt/JwtTokenProvider.java
- src/main/java/banzzac/jwt/LoginDTO.java
- src/main/java/banzzac/jwt/LoginServiceImpl.java
- src/main/java/banzzac/jwt/MemberDetail.java
- src/main/java/banzzac/mapper/AdminMapper.java
- src/main/java/banzzac/mapper/LoginMapper.java
- src/main/java/banzzac/rest/LoginController.java
- src/main/resources/application.yml
관리자 페이지로 전환 되도록 수정해야 함. 
JWT를 어떻게 PingPong 해야하는 지 아직 미구현,
Front 연결 후에 실험하도록 하겠음
> feat: JWT Token 발급 완료, 검증 및 재발급 실험 전
